import { NodeConfig } from "./types";

export const localVisionNodeConfig: NodeConfig = {
  nodeName: "Local Vision",
  processorType: "local-vision",
  icon: "FaEye",
  inputNames: ["image_url", "prompt"],
  fields: [
    {
      name: "model",
      label: "Model",
      type: "textfield",
      placeholder: "e.g. llava-1.6",
    },
    {
      name: "prompt",
      label: "Prompt",
      type: "textarea",
      required: true,
      hasHandle: true,
      placeholder: "Enter prompt",
    },
    {
      name: "image_url",
      label: "Image",
      type: "fileUpload",
      hasHandle: true,
      required: true,
      placeholder: "Image URL",
      canAddChildrenFields: true,
    },
    {
      name: "temperature",
      label: "Temperature",
      type: "numericfield",
      defaultValue: 0.7,
      min: 0,
      max: 2,
      step: 0.1,
      allowDecimal: true,
    },
    {
      name: "max_tokens",
      label: "Max Tokens",
      type: "numericfield",
      defaultValue: 1024,
      min: 1,
      step: 1,
    },
    {
      name: "top_p",
      label: "Top P",
      type: "numericfield",
      defaultValue: 1,
      min: 0,
      max: 1,
      step: 0.05,
      allowDecimal: true,
    },
    {
      name: "seed",
      label: "Seed",
      type: "numericfield",
      min: 0,
      step: 1,
    },
    {
      name: "endpoint_url",
      label: "Endpoint URL",
      type: "textfield",
      placeholder: "http://localhost:8001/vision",
    },
  ],
  outputType: "markdown",
  showHandlesNames: true,
  section: "models",
  helpMessage: "gptVisionPromptHelp",
};
