import { NodeConfig } from "./types";

export const localLlmNodeConfig: NodeConfig = {
  nodeName: "Local LLM",
  processorType: "local-llm",
  icon: "FaRobot",
  inputNames: ["prompt", "context"],
  fields: [
    {
      name: "model",
      label: "Model",
      type: "textfield",
      placeholder: "e.g. llama3-8b",
    },
    {
      name: "context",
      label: "Context",
      type: "textarea",
      hasHandle: true,
      placeholder: "Optional context",
    },
    {
      name: "prompt",
      label: "Prompt",
      type: "textarea",
      required: true,
      hasHandle: true,
      placeholder: "Enter prompt",
    },
    {
      name: "temperature",
      label: "Temperature",
      type: "numericfield",
      defaultValue: 0.7,
      min: 0,
      max: 2,
      step: 0.1,
      allowDecimal: true,
    },
    {
      name: "max_tokens",
      label: "Max Tokens",
      type: "numericfield",
      defaultValue: 1024,
      min: 1,
      step: 1,
    },
    {
      name: "top_p",
      label: "Top P",
      type: "numericfield",
      defaultValue: 1,
      min: 0,
      max: 1,
      step: 0.05,
      allowDecimal: true,
    },
    {
      name: "seed",
      label: "Seed",
      type: "numericfield",
      min: 0,
      step: 1,
    },
    {
      name: "endpoint_url",
      label: "Endpoint URL",
      type: "textfield",
      placeholder: "http://localhost:8001/llm",
    },
  ],
  outputType: "markdown",
  showHandlesNames: true,
  section: "models",
  helpMessage: "llmPromptHelp",
};
