import { NodeConfig } from "./types";

export const mainVisionModelNodeConfig: NodeConfig = {
  nodeName: "Main Vision Model",
  processorType: "main-vision-model",
  icon: "FaEye",
  showHandlesNames: true,
  inputNames: ["input_url"],
  fields: [
    {
      name: "input_url",
      label: "Input URL / Stream Ref",
      type: "input",
      hasHandle: true,
      required: true,
      placeholder: "/asset/file.jpg or stream://<id>",
    },
    {
      name: "model_path",
      label: "Model Path",
      type: "textfield",
      defaultValue: "models/yolov5mu.pt",
      placeholder: "e.g. models/yolov5mu.pt",
    },
    {
      name: "conf_threshold",
      label: "Confidence",
      type: "numericfield",
      defaultValue: 0.25,
      min: 0,
      max: 1,
      step: 0.01,
      allowDecimal: true,
    },
    {
      name: "stream_fps",
      label: "Stream FPS",
      type: "numericfield",
      defaultValue: 12,
      min: 1,
      max: 30,
      step: 1,
      allowDecimal: false,
    },
    {
      name: "inference_fps",
      label: "Inference FPS",
      type: "numericfield",
      defaultValue: 6,
      min: 1,
      max: 30,
      step: 1,
      allowDecimal: false,
    },
    {
      name: "imgsz",
      label: "Inference Size",
      type: "numericfield",
      defaultValue: 512,
      min: 160,
      max: 1280,
      step: 32,
      allowDecimal: false,
    },
    {
      name: "classes",
      label: "Classes Filter (optional)",
      type: "list",
      defaultValue: [],
      placeholder: "e.g. person,car or 0,2",
    },
    {
      name: "enable_ergonomic_check",
      label: "Ergonomic Check",
      type: "switch",
      defaultValue: false,
    },
    {
      name: "ergonomic_pose_model_path",
      label: "Pose Model Path",
      type: "textfield",
      defaultValue: "models/yolov8n-pose.pt",
      placeholder: "e.g. models/yolov8n-pose.pt",
      condition: {
        field: "enable_ergonomic_check",
        operator: "equals",
        value: true,
      },
    },
    {
      name: "ergonomic_min_keypoint_conf",
      label: "Min Keypoint Confidence",
      type: "numericfield",
      defaultValue: 0.35,
      min: 0,
      max: 1,
      step: 0.01,
      allowDecimal: true,
      condition: {
        field: "enable_ergonomic_check",
        operator: "equals",
        value: true,
      },
    },
  ],
  outputType: "markdown",
  section: "models",
  category: "processing",
  helpMessage:
    "Run YOLO on file/stream with optional ergonomic pose check. Local-first: model files must exist locally (no auto-download).",
};
