import { NodeConfig } from "./types";

export const ocrReaderNodeConfig: NodeConfig = {
  nodeName: "OCR Reader",
  processorType: "ocr-reader",
  icon: "AiOutlineSearch",
  showHandlesNames: true,
  inputNames: ["input_url"],
  fields: [
    {
      name: "input_url",
      label: "Input (asset or stream)",
      type: "input",
      hasHandle: true,
      required: true,
      placeholder: "/asset/<image>.jpg or stream://<id>",
    },
    {
      name: "lang",
      label: "Language",
      type: "textfield",
      defaultValue: "",
      placeholder: "Auto / search server languages (e.g. eng+ind)",
      description:
        "Search and choose from server OCR languages, or type manually (e.g. eng+ind). Leave empty for auto.",
    },
    {
      name: "ocr_profile",
      label: "OCR Preset",
      type: "select",
      defaultValue: "general",
      options: [
        { label: "General", value: "general" },
        { label: "UI Screenshot (Explorer/App)", value: "ui-screenshot" },
        { label: "Document", value: "document" },
        { label: "Single Line", value: "single-line" },
      ],
      description:
        "Recommended defaults for common cases. Use Advanced only if needed.",
    },
    {
      name: "show_advanced",
      label: "Advanced Settings",
      type: "switch",
      defaultValue: false,
    },
    {
      name: "psm",
      label: "Page Segmentation (PSM)",
      type: "select",
      defaultValue: "6",
      options: [
        { label: "3 - Auto (default page)", value: "3" },
        { label: "4 - Single column", value: "4" },
        { label: "6 - Single uniform block", value: "6" },
        { label: "7 - Single text line", value: "7" },
        { label: "8 - Single word", value: "8" },
        { label: "11 - Sparse text", value: "11" },
        { label: "13 - Raw line", value: "13" },
      ],
      condition: {
        field: "show_advanced",
        operator: "equals",
        value: true,
      },
    },
    {
      name: "oem",
      label: "OCR Engine (OEM)",
      type: "select",
      defaultValue: "3",
      options: [
        { label: "3 - Default", value: "3" },
        { label: "1 - LSTM only", value: "1" },
        { label: "0 - Legacy only", value: "0" },
        { label: "2 - Legacy + LSTM", value: "2" },
      ],
      condition: {
        field: "show_advanced",
        operator: "equals",
        value: true,
      },
    },
    {
      name: "preprocess",
      label: "Preprocess",
      type: "select",
      defaultValue: "auto",
      options: [
        { label: "Auto (threshold)", value: "auto" },
        { label: "Adaptive threshold", value: "adaptive" },
        { label: "Gray", value: "gray" },
        { label: "Threshold", value: "threshold" },
        { label: "None", value: "none" },
      ],
      condition: {
        field: "show_advanced",
        operator: "equals",
        value: true,
      },
    },
    {
      name: "scale_factor",
      label: "Scale Factor",
      type: "numericfield",
      defaultValue: 1.8,
      min: 1,
      max: 4,
      step: 0.1,
      allowDecimal: true,
      description: "Upscale image before OCR. Helpful for small UI text.",
      condition: {
        field: "show_advanced",
        operator: "equals",
        value: true,
      },
    },
    {
      name: "min_confidence",
      label: "Min Confidence",
      type: "numericfield",
      defaultValue: 15,
      min: 0,
      max: 100,
      step: 1,
      allowDecimal: true,
      description: "Ignore OCR words below this confidence score (0-100).",
      condition: {
        field: "show_advanced",
        operator: "equals",
        value: true,
      },
    },
    {
      name: "stream_fps",
      label: "Stream FPS",
      type: "numericfield",
      defaultValue: 10,
      min: 1,
      max: 30,
      step: 1,
      allowDecimal: false,
      description: "Overlay stream output frame rate.",
      condition: {
        field: "show_advanced",
        operator: "equals",
        value: true,
      },
    },
    {
      name: "ocr_fps",
      label: "OCR FPS",
      type: "numericfield",
      defaultValue: 2,
      min: 0.2,
      max: 15,
      step: 0.1,
      allowDecimal: true,
      description: "How often OCR runs on stream frames (lower = lighter CPU).",
      condition: {
        field: "show_advanced",
        operator: "equals",
        value: true,
      },
    },
    {
      name: "draw_boxes",
      label: "Draw Boxes (stream)",
      type: "switch",
      defaultValue: true,
      condition: {
        field: "show_advanced",
        operator: "equals",
        value: true,
      },
    },
    {
      name: "draw_text",
      label: "Draw Text (stream)",
      type: "switch",
      defaultValue: true,
      condition: {
        field: "show_advanced",
        operator: "equals",
        value: true,
      },
    },
    {
      name: "tesseract_config",
      label: "Extra Tesseract Config",
      type: "textfield",
      defaultValue: "",
      placeholder: "Optional (e.g. -c preserve_interword_spaces=1)",
      description: "Advanced: extra flags passed to Tesseract.",
      condition: {
        field: "show_advanced",
        operator: "equals",
        value: true,
      },
    },
  ],
  outputType: "markdown",
  section: "tools",
  category: "processing",
  helpMessage:
    "Simple OCR for images/streams. Choose a language and preset first. Use Advanced only when results need tuning.",
};
