import { NodeConfig } from "./types";

export const roiNodeConfig: NodeConfig = {
  nodeName: "ROI",
  processorType: "roi",
  icon: "MdOutlineCrop",
  showHandlesNames: false,
  inputNames: ["input_url"],
  fields: [
    {
      name: "input_url",
      label: "URL video / ref video",
      type: "input",
      hasHandle: true,
      required: true,
      placeholder: "/asset/<image|video> or stream://<id>",
    },
    {
      name: "width",
      label: "Width (px)",
      type: "numericfield",
      defaultValue: 120,
      min: 1,
      step: 1,
      allowDecimal: false,
    },
    {
      name: "height",
      label: "Height (px)",
      type: "numericfield",
      defaultValue: 120,
      min: 1,
      step: 1,
      allowDecimal: false,
    },
    {
      name: "x",
      type: "numericfield",
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 0.001,
      allowDecimal: true,
      hidden: true,
    },
    {
      name: "y",
      type: "numericfield",
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 0.001,
      allowDecimal: true,
      hidden: true,
    },
    {
      name: "w",
      type: "numericfield",
      defaultValue: 1,
      min: 0,
      max: 1,
      step: 0.001,
      allowDecimal: true,
      hidden: true,
    },
    {
      name: "h",
      type: "numericfield",
      defaultValue: 1,
      min: 0,
      max: 1,
      step: 0.001,
      allowDecimal: true,
      hidden: true,
    },
  ],
  outputType: "markdown",
  section: "tools",
  category: "processing",
  helpMessage: "Preview ROI box on media and output cropped image/video/stream",
};
